### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by mstuttgart** [multidadosti-erp/odoo-brasil-addons#46]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [x] br_account @mstuttgart https://github.com/multidadosti-erp/odoo-brasil-addons/pull/50
- [x] br_account_einvoice @mstuttgart https://github.com/multidadosti-erp/odoo-brasil-addons/pull/54
- [x] br_account_payment @aldo774 https://github.com/multidadosti-erp/odoo-brasil-addons/pull/52
- [ ] ~br_bank_statement_import~ Nao utilizado
- [x] br_base @mstuttgart https://github.com/multidadosti-erp/odoo-brasil-addons/pull/47
- [x] br_boleto @rodrigets https://github.com/multidadosti-erp/odoo-brasil-addons/pull/54
- [ ] ~br_cnab~ (não usado)
- [x] br_coa @mstuttgart https://github.com/multidadosti-erp/odoo-brasil-addons/pull/50
- [x] br_crm @mstuttgart https://github.com/multidadosti-erp/odoo-brasil-addons/pull/48
- [x] br_crm_zip @mstuttgart https://github.com/multidadosti-erp/odoo-brasil-addons/pull/53
- [x] br_data_account @mstuttgart https://github.com/multidadosti-erp/odoo-brasil-addons/pull/50
- [x] br_data_account_product @mstuttgart https://github.com/multidadosti-erp/odoo-brasil-addons/pull/50
- [x] br_data_base @mstuttgart https://github.com/multidadosti-erp/odoo-brasil-addons/pull/49
- [ ] ~br_delivery~ Não instalavel
- [x] br_hr  @mstuttgart https://github.com/multidadosti-erp/odoo-brasil-addons/pull/59
- [x] br_hr_payroll  @mstuttgart https://github.com/multidadosti-erp/odoo-brasil-addons/pull/59
- [x] br_hr_payroll_account  @mstuttgart https://github.com/multidadosti-erp/odoo-brasil-addons/pull/59
- [x] br_nfe @mstuttgart https://github.com/multidadosti-erp/odoo-brasil-addons/pull/55
- [x] br_nfse @mstuttgart https://github.com/multidadosti-erp/odoo-brasil-addons/pull/57
- [x] ~br_nfse_ginfes~
- [x] br_nfse_paulistana @mstuttgart https://github.com/multidadosti-erp/odoo-brasil-addons/pull/57
- [x] ~br_nfse_simpless~
- [x] ~br_nfse_susesu~
- [ ] ~br_point_sale~ Nao utilizado
- [x] br_purchase @mstuttgart https://github.com/multidadosti-erp/odoo-brasil-addons/pull/62
- [x] br_purchase_stock @mstuttgart https://github.com/multidadosti-erp/odoo-brasil-addons/pull/63
- [x] br_sale @mstuttgart https://github.com/multidadosti-erp/odoo-brasil-addons/pull/58
- [x] br_sale_stock @mstuttgart https://github.com/multidadosti-erp/odoo-brasil-addons/pull/61
- [x] br_stock_account @mstuttgart https://github.com/multidadosti-erp/odoo-brasil-addons/pull/60
- [ ] ~br_website_sale~ Não utilizado
- [x] br_zip @mstuttgart https://github.com/multidadosti-erp/odoo-brasil-addons/pull/53
